name: Análisis Dinámico (DAST)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dast:
    name: Escaneo OWASP ZAP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Iniciar Servidor de Prueba
        run: |
          npm install -g http-server
          npx http-server . -p 5173 &
          # Esperamos a que el puerto responda
          npx wait-on http://127.0.0.1:5173 -t 60000

      - name: Escaneo ZAP Baseline (Docker)
        run: |
          docker run --rm --network host \
          -v ${{ github.workspace }}:/zap/wrk/:rw \
          -u 0 \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t http://localhost:5173 \
          -r zap_report.html \
          -I

      - name: Guardar resultados ZAP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: zap_report.html **